# Generated by Django 2.2.6 on 2019-10-24 14:37

from django.db import migrations
from django.contrib.postgres.fields import HStoreField


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='properties',
            field=HStoreField(blank=True, null=True),
        ),
    ]
