# Generated by Django 2.2.6 on 2019-10-25 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0002_auto_20191024_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('Draft', 'Draft'), ('Available', 'Available'), ('Deprecated', 'Deprecated')], default='Draft', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('is_removed', models.BooleanField(default=False)),
                ('root_package_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='project_url',
            field=models.URLField(blank=True, help_text='Trello project URL', null=True),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('file_type', models.CharField(choices=[('Document', 'Document'), ('Sheet', 'Sheet'), ('Other', 'Other')], default='Document', max_length=15)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_driven_acquisition.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
