# Generated by Django 2.2.6 on 2019-10-28 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_driven_acquisition', '0003_auto_20191025_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('access_level', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Admin', 'Admin')], max_length=10)),
                ('asset_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_driven_acquisition.File')),
                ('asset_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_driven_acquisition.Folder')),
                ('asset_package_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_driven_acquisition.PackageTemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
