# Generated by Django 2.2.6 on 2019-10-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0004_acl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'get_latest_by': 'created_at', 'permissions': (('can_edit_content', 'Can edit file content'),)},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'get_latest_by': 'created_at', 'permissions': (('can_set_properties', 'Can set properties on folder'), ('can_propagate_properties', 'Can propagate properties to children.'), ('can_edit_child_content', 'Can edit content of children.'))},
        ),
        migrations.AlterModelOptions(
            name='packagetemplate',
            options={'get_latest_by': 'created_at', 'permissions': (('can_deploy', 'Can deploy from template'),)},
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='title',
            field=models.CharField(default='lorem ipsum', max_length=256),
            preserve_default=False,
        ),
    ]
