# Generated by Django 2.2.6 on 2019-10-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0007_auto_20191029_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data_driven_acquisition.Folder'),
        ),
    ]
