# Generated by Django 2.2.6 on 2019-10-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0008_auto_20191031_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='project_url',
        ),
        migrations.AddField(
            model_name='folder',
            name='project_card_id',
            field=models.URLField(blank=True, help_text='Trello Card IDL', null=True),
        ),
    ]
