# Generated by Django 2.2.6 on 2019-11-15 22:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0009_auto_20191031_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean')], default='Document', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.RemoveField(
            model_name='packagetemplate',
            name='properties',
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='data_driven_acquisition.Folder')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='data_driven_acquisition.PackageProperty')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='packagetemplate',
            name='properties',
            field=models.ManyToManyField(related_name='packages', to='data_driven_acquisition.PackageProperty'),
        ),
    ]
