# Generated by Django 2.2.6 on 2019-11-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0010_auto_20191115_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='properties',
        ),
    ]
