# Generated by Django 2.2.6 on 2019-11-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0011_remove_folder_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'get_latest_by': 'created_at', 'permissions': (('can_set_properties', 'Can set properties on folder'), ('can_propagate_properties', 'Can propagate properties to children.'), ('can_edit_child_content', 'Can edit content of children.')), 'verbose_name_plural': 'Folders & Packages'},
        ),
        migrations.AlterModelOptions(
            name='packageproperty',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': 'Packages Properties'},
        ),
        migrations.AlterModelOptions(
            name='packagetemplate',
            options={'get_latest_by': 'created_at', 'permissions': (('can_deploy', 'Can deploy package from template'),), 'verbose_name_plural': 'Packages Templates'},
        ),
        migrations.AddField(
            model_name='packageproperty',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageproperty',
            name='property_type',
            field=models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('list', 'list')], default='Document', max_length=15),
        ),
    ]
