# Generated by Django 2.2.6 on 2019-11-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0012_auto_20191115_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='data_driven_acquisition.Folder'),
        ),
    ]
