# Generated by Django 2.2.6 on 2019-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0014_auto_20191117_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageproperty',
            name='tab',
            field=models.CharField(choices=[('General', 'General'), ('Market Research', 'Market Research'), ('List', 'List')], default='General', max_length=15),
        ),
    ]
