# Generated by Django 2.2.6 on 2019-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0015_packageproperty_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproperty',
            name='tab',
            field=models.CharField(choices=[('General', 'General'), ('Market Research', 'Market Research'), ('Team', 'Team'), ('RFQ', 'RFQ'), ('RFI', 'RFI')], default='General', max_length=15),
        ),
    ]
