# Generated by Django 2.2.6 on 2019-12-19 19:32

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0016_auto_20191118_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='project_card_id',
            field=models.CharField(blank=True, help_text='Trello Card ID', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='00 - Unassigned', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='data_driven_acquisition.Folder'),
        ),
    ]
