# Generated by Django 2.2.9 on 2020-01-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0017_auto_20191219_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': 'Property Values'},
        ),
        migrations.AlterField(
            model_name='packageproperty',
            name='property_type',
            field=models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('List', 'List'), ('Date', 'Date')], default='Document', max_length=15),
        ),
        migrations.AlterField(
            model_name='packageproperty',
            name='tab',
            field=models.CharField(choices=[('1 General Information', '1 General Information'), ('2 Acquisition Overview', '2 Acquisition Overview'), ('3 Requirements Document', '3 Requirements Document'), ('4 Market Research', '4 Market Research'), ('5 Solicitation/Evaluation', '5 Solicitation/Evaluation'), ('6 Pre-Award', '6 Pre-Award'), ('7 Modification', '7 Modification')], default='General', max_length=15),
        ),
    ]
