# Generated by Django 2.2.9 on 2020-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0018_auto_20200127_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproperty',
            name='property_type',
            field=models.CharField(choices=[('String', 'String'), ('Text', 'Text'), ('Number', 'Number'), ('Integer', 'Integer'), ('Boolean', 'Boolean'), ('List', 'List'), ('Date', 'Date')], default='Document', max_length=50),
        ),
    ]
