# Generated by Django 3.1 on 2020-08-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_driven_acquisition', '0021_folder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageproperty',
            name='tab',
            field=models.CharField(choices=[('1 General Information', '1 General Information'), ('2 Acquisition Overview', '2 Acquisition Overview'), ('3 Requirements Document', '3 Requirements Document'), ('4 Market Research', '4 Market Research'), ('5 Solicitation/Evaluation', '5 Solicitation/Evaluation'), ('6 Pre-Award', '6 Pre-Award'), ('7 ModificationIAA 000 - General', '7 ModificationIAA 000 - General'), ('IIA 001 - 7600A', 'IIA 001 - 7600A'), ('IAA 002 - 7600A Additional', 'IAA 002 - 7600A Additional'), ('IAA 003 - 7600B', 'IAA 003 - 7600B'), ('IAA 004 - SOW', 'IAA 004 - SOW'), ('IAA 008 - FITARA review', 'IAA 008 - FITARA review')], default='General', max_length=50),
        ),
    ]
